###
POST http://localhost:9000/api/exportacion HTTP/1.1
Content-Type: application/json

{
  "Producto": "fresa",
  "Cantidad": 10,
  "ValorKilo": 5.0,
  "ValorTotal": 50.0
}


###
GET http://localhost:9000/api/exportacion HTTP/1.1

###
GET http://localhost:9000/api/exportacion/6600def667333ae5dea83d4d HTTP/1.1
###

PUT  http://localhost:9000/api/exportacion/660347426d759e9b3caaa0e8 HTTP/1.1
Content-Type: application/json

{
    "_id": "660347426d759e9b3caaa0e8",
    "Producto": "mortadelita6",
    "Cantidad": 4,
    "ValorKilo": 3900,
    "ValorTotal": 3,
    "__v": 0
  }

###
DELETE http://localhost:9000/api/exportacion/6601b5b465b2b09523bf6fe8 HTTP/1.1